import 'package:ailoitte/Model/dataModel.dart';
import 'package:ailoitte/service/http_Services.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class ListController extends GetxController{

  

    RxString searchInput = "".obs;

   RxBool issearch = false.obs;
   @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    // value.searchApi();

  }

  RxList<Drinks> searchList= <Drinks>[].obs;
  

  final baseUrl = "https://thecocktaildb.com/api/json/v1/1/search.php?s=";

  searchApi() async {
  Dio dio = Dio();

  print("hellooo$searchInput");

  try {

    if(searchInput == ""){
       Get.snackbar("Search Empty", "Please search anything",backgroundColor: Colors.red);
      
    }else{
     var apiUrl = ("${baseUrl}$searchInput");

  final response = await dio.get(apiUrl);

  Autogenerated products = Autogenerated.fromJson(response.data);

  if(products != null){
   searchList.value = products.drinks!;
   print("hhhhhhhhh$searchList");
  }else{
  }
  
  return products;
    }
    
  } catch (e) {
    Get.snackbar("No Data", "Result not found",backgroundColor: Colors.red);
  }
 

}
  }
  
