// import 'package:json_annotation/json_annotation.dart';

// part 'dataModel.g.dart';

// @JsonSerializable()
// class Data {
//   @JsonKey(name : "strDrink")
//   String? name;

//   @JsonKey(name : "strDrinkThumb")
//   String? image;

//   @JsonKey(name : "strInstructions")
//   String? description;

//   @JsonKey(name : "strIngredient1")
//   String? ingredient1;

//   @JsonKey(name : "strIngredient2")
//   String? ingredient2;

//    @JsonKey(name : "strAlchololic")
//   String? alcoholic;

//    @JsonKey(name : "strCategory")
//   String? category;

//   Data();

//   factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson(json);
//   Map<String, dynamic> toJson() => _$DataToJson(this);
// }
import 'package:json_annotation/json_annotation.dart';

 part 'dataModel.g.dart';
@JsonSerializable()
class Autogenerated {
  @JsonKey(name : "drinks")
  List<Drinks>? drinks;

  Autogenerated({this.drinks});

     factory Autogenerated.fromJson(Map<String, dynamic> json) => _$AutogeneratedFromJson(json);

 
}
@JsonSerializable()
class Drinks {
   @JsonKey(name : "strDrink")
  String? name;

  @JsonKey(name : "strDrinkThumb")
  String? image;

  @JsonKey(name : "strInstructions")
  String? description;

  @JsonKey(name : "strIngredient1")
  String? ingredient1;

  @JsonKey(name : "strIngredient2")
  String? ingredient2;

   @JsonKey(name : "strAlchololic")
  String? alcoholic;

   @JsonKey(name : "strCategory")
  String? category;

  Drinks();

  factory Drinks.fromJson(Map<String, dynamic> json) => _$DrinksFromJson(json);
  Map<String, dynamic> toJson() => _$DrinksToJson(this);
  }

